runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"

# Only use one instance
manual_scaling:
  instances: 1

# Use low resources during development and test
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Define entrypoint to start the app
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "music-event-app-442810-firebase-adminsdk-szww8-3fa59e6748.json"
  FIREBASE_BUCKET: "music-event-app-442810.firebasestorage.app"
  GOOGLE_OAUTH_CREDENTIALS: "client_secret_568353778562-h90rvnvs5vfd1hsae6mq1eh6ircpal4e.apps.googleusercontent.com.json"
  FRONTEND_REGISTER: "https://music-event-app-frontend.lm.r.appspot.com/register"
  FLASK_SECRET_KEY: "music-event-app-442810"
  FRONTEND_URL: "https://music-event-app-frontend.lm.r.appspot.com"
  BACKEND_ENDPOINT: "https://music-event-app-442810.ew.r.appspot.com"
  CLOUD_ENDPOINT: "https://music-event-app-442810.ew.r.appspot.com"