runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"

# Only use one instance
manual_scaling:
  instances: 1

# Use low resources during development and test
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Define entrypoint to start the app
entrypoint: gunicorn -b :$PORT main:app